name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make

    - name: Setup Python
      uses: actions/setup-python@v5.5.0
      with:
        python-version: 3.12

    - name: Run tests
      run: python3 tests/test.py
